[query]
max_active_sessions = 300
shutdown_wait_timeout_ms=15000

flight_api_address = "0.0.0.0:9091"
admin_api_address = "0.0.0.0:8080"
metric_api_address = "0.0.0.0:7070"

mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

http_handler_host = "0.0.0.0"
http_handler_port = 8000

flight_sql_handler_host = "0.0.0.0"
flight_sql_handler_port = 8900

tenant_id = "wubx"
cluster_id = "default"

table_engine_memory_enabled = true
default_storage_format = 'parquet'

#default_compression = 'lz4'
max_memory_limit_enabled=true
max_server_memory_usage=54975581388

#enable_udf_server = true
#udf_server_allow_insecure = true
#udf_server_allow_list = ['http://192.168.1.201:8815']

#[[setttings]]
#max_storage_io_requests=6

[[query.users]]
name = "root"
auth_type = "no_password"

[log]

[log.file]
level = "INFO"
limit = 24
format = "text"
include_node_id=true
dir = "/var/log/databend"

[log.query]
on = true

[log.profile]
on = true
dir = "/var/log/databend/profile/"

[meta]
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60

[storage]
type = "s3"
allow_insecure = true
[storage.s3]
bucket = "databend"
root="t1001"
endpoint_url = "http://127.0.0.1:9000"
access_key_id = "rustfsadmin"
secret_access_key = "rustfsadmin"
#enable_virtual_host_style = false

#[spill]
#spill_local_disk_path = '/data/databend/3307/spill/'
#spill_local_disk_reserved_space_percentage = 5

#[spill.storage]
#type = "s3"
#[spill.storage.s3]
#bucket = "myspill"
#root = "admin"
#endpoint_url = "http://192.168.1.100:9900"
#access_key_id = "minioadmin"
#secret_access_key = "minioadmin"
#allow_insecure = true

[cache]
table_data_cache_population_queue_size = 64
data_cache_storage = "none"
enable_table_meta_cache = true
table_data_deserialized_data_bytes =1073741824
enable_table_bloom_index_cache=true
table_bloom_index_meta_count=3000
table_bloom_index_filter_size=1073741824

[cache.disk]
path = "/var/lib/databend/cache"
max_bytes = 21474836480
